name = "tankflow"
version = "0.1.0"
license = "license"
author = "Eric Le Pen"
maintainer = "eric.lepen@autoliv.com"
copyright = "Copyright 2024, Eric Le Pen"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

